spring.application.name:
  shopping-app
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/shopping?useSSL=true&serverTimezone=GMT%2B8
  main:
    allow-circular-references: true
  jackson:
      deserialization:
        fail-on-unknown-properties: false
      default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:com/example/shopping-app/mapper/*.xml
  type-aliases-package: com.example.test.dataObject
  configuration:
    map-underscore-to-camel-case: true

